### ISSUE TITLE
RoadMap: Vite extension for ESM mode VSCode

### ISSUE THREAD

**Issue by FossPrime** [FossPrime/webcontainer#1]
- [ ] Get XTerm doing something
- [ ] Get data link / proxy hooked up (seems like a lot of firewall problems)
  - [ ]  Make Chrome extension to bypass cors... See gitlab Cors bypass extension and Vite for Chrome extensions
- [ ] PWA File opening
- [ ] Foldable phone layout
- [ ] Publish to market, CodeOSS & StackBlitz
- [ ] Test workflows
